#!/usr/bin/env python3
import json, os

ROOT = os.getcwd()

def join_chunks(v):
    return "".join(v) if isinstance(v, list) else v

PATCHES = json.loads(r'''[
  {
    "file": "src/app/api/cart/route.ts",
    "old": [
      "import { NextRequest, NextResponse } from \"next/server\";\nimport mongoose from \"mongoose\";\nimport connectDB from \"@/lib/mongodb\";\nimport Cart from \"@/models/Cart\";\nimport Product from \"@/models/Product\";\n\nfunction getUserId(request: NextRequest) {\n  return request.headers.get(\"x-user-id\")?.trim() || \"\";\n}\n\nexport async function GET(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const cart = await Cart.findOne({ userId }).lean();\n\n    return NextResponse.json({\n      success: true,\n      cart: cart || {\n        userId,\n        items: [],\n      },\n    });\n  } catch (error) {\n    console.error(\"GET cart error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to load cart.\",\n      },\n      { status: 500 }\n    );\n  }\n}\nexport async function POST(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const body = await request.json();\n\n    const productId = body.productId;\n    const quantity = Number(body.quantity || 1);\n\n    if (\n      !productId ||\n      !mongoose.Types.ObjectId.isValid(productId)\n    ) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Valid product ID is required.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    if (!Number.isInteger(quantity) || quantity < 1) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Quantity must be at least 1.\",\n        },\n        { status: 400 }\n      )",
      ";\n    }\n\n    const product = await Product.findById(productId).lean();\n\n    if (!product) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Product not found.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    if (!product.active) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"This product is currently inactive.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    if (product.stock < quantity) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: `Only ${product.stock} items are available.`,\n        },\n        { status: 400 }\n      );\n    }\n\n    let cart = await Cart.findOne({ userId });\n\n    if (!cart) {\n      cart = new Cart({\n        userId,\n        items: [],\n      });\n    }\n\n    const existingItem = cart.items.find(\n      (item) =>\n        item.productId.toString() === productId\n    );\n\n    if (existingItem) {\n      const newQuantity =\n        existingItem.quantity + quantity;\n\n      if (newQuantity > product.stock) {\n        return NextResponse.json(\n          {\n            success: false,\n            message: `Only ${product.stock} items are available.`,\n          },\n          { status: 400 }\n        );\n      }\n\n      existingItem.quantity = newQuantity;\n      existingItem.price = product.price;\n      existingItem.name = product.name;\n      existingItem.image = product.image;\n    } else {\n      cart.items.push({\n        productId: new mongoose.Types.ObjectId(productId),\n        name: product.name,\n        price: product.price,\n        quantity,\n        image: product.image,\n      });\n    }\n\n    await cart.save();\n\n    return NextResponse.json({\n      success: true,\n      message: \"Product added to cart.\",\n      cart,\n    });\n  } catch (error) {\n    console.error(\"POST cart error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to add product to cart.\",\n      },\n      { status: 500 }\n ",
      "   );\n  }\n}\nexport async function PATCH(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const body = await request.json();\n\n    const productId = body.productId;\n    const quantity = Number(body.quantity);\n\n    if (\n      !productId ||\n      !mongoose.Types.ObjectId.isValid(productId)\n    ) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Valid product ID is required.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    if (!Number.isInteger(quantity) || quantity < 1) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Quantity must be at least 1.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    const product = await Product.findById(productId).lean();\n\n    if (!product) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Product not found.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    if (quantity > product.stock) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: `Only ${product.stock} items are available.`,\n        },\n        { status: 400 }\n      );\n    }\n\n    const cart = await Cart.findOne({ userId });\n\n    if (!cart) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Cart not found.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    const item = cart.items.find(\n      (cartItem) =>\n        cartItem.productId.toString() === productId\n    );\n\n    if (!item) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Product is not in the cart.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    item.quantity = quantity;\n    item.price =",
      " product.price;\n    item.name = product.name;\n    item.image = product.image;\n\n    await cart.save();\n\n    return NextResponse.json({\n      success: true,\n      message: \"Cart updated successfully.\",\n      cart,\n    });\n  } catch (error) {\n    console.error(\"PATCH cart error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to update cart.\",\n      },\n      { status: 500 }\n    );\n  }\n}\nexport async function DELETE(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const { searchParams } = new URL(request.url);\n    const productId =\n      searchParams.get(\"productId\")?.trim() || \"\";\n\n    if (productId) {\n      if (!mongoose.Types.ObjectId.isValid(productId)) {\n        return NextResponse.json(\n          {\n            success: false,\n            message: \"Invalid product ID.\",\n          },\n          { status: 400 }\n        );\n      }\n\n      const cart = await Cart.findOne({ userId });\n\n      if (!cart) {\n        return NextResponse.json({\n          success: true,\n          message: \"Cart is already empty.\",\n          cart: {\n            userId,\n            items: [],\n          },\n        });\n      }\n\n      cart.items = cart.items.filter(\n        (item) =>\n          item.productId.toString() !== productId\n      );\n\n      await cart.save();\n\n      return NextResponse.json({\n        success: true,\n        message: \"Product removed from cart.\",\n        cart,\n      });\n    }\n\n    await Cart.findOneAndDelete({ userId });\n\n    return NextResponse.json({\n      success: true,\n      message: \"Cart cleared successfully.\",\n      cart: {\n        userId,\n        items: [],\n      },\n    });\n  } catch (error) {\n    console.error(\"DELETE cart error:\", error);\n\n    retu",
      "rn NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to update cart.\",\n      },\n      { status: 500 }\n    );\n  }\n}\n\n"
    ],
    "new": [
      "import { NextRequest, NextResponse } from \"next/server\";\nimport mongoose from \"mongoose\";\nimport connectDB from \"@/lib/mongodb\";\nimport Cart from \"@/models/Cart\";\nimport Product from \"@/models/Product\";\n\nfunction getUserId(request: NextRequest) {\n  return request.headers.get(\"x-user-id\")?.trim() || \"\";\n}\n\nexport async function GET(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const cart = await Cart.findOne({ userId }).lean();\n\n    return NextResponse.json({\n      success: true,\n      cart: cart || {\n        userId,\n        items: [],\n      },\n    });\n  } catch (error) {\n    console.error(\"GET cart error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to load cart.\",\n      },\n      { status: 500 }\n    );\n  }\n}\nexport async function POST(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const body = await request.json();\n\n    const productId = body.productId;\n    const quantity = Number(body.quantity || 1);\n\n    if (\n      !productId ||\n      !mongoose.Types.ObjectId.isValid(productId)\n    ) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Valid product ID is required.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    if (!Number.isInteger(quantity) || quantity < 1) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Quantity must be at least 1.\",\n        },\n        { status: 400 }\n      )",
      ";\n    }\n\n    const product = await Product.findById(productId).lean();\n\n    if (!product) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Product not found.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    if (!product.active) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"This product is currently inactive.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    if (product.stock < quantity) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: `Only ${product.stock} items are available.`,\n        },\n        { status: 400 }\n      );\n    }\n\n    let cart = await Cart.findOne({ userId });\n\n    const existingItem = cart?.items.find(\n      (item) => item.productId.toString() === productId\n    );\n\n    if (existingItem) {\n      const newQuantity = existingItem.quantity + quantity;\n\n      if (newQuantity > product.stock) {\n        return NextResponse.json(\n          {\n            success: false,\n            message: `Only ${product.stock} items are available.`,\n          },\n          { status: 400 }\n        );\n      }\n\n      cart = await Cart.findOneAndUpdate(\n        { userId, \"items.productId\": productId },\n        {\n          $set: {\n            \"items.$.quantity\": newQuantity,\n            \"items.$.price\": product.price,\n            \"items.$.name\": product.name,\n            \"items.$.image\": product.image,\n          },\n        },\n        { new: true }\n      );\n    } else {\n      // Atomic upsert: avoids a race where two rapid requests (e.g. a\n      // double-tap) both see \"no cart yet\" and both try to create one,\n      // which previously could throw a duplicate-key error on the\n      // unique userId index and surface as a generic 500 error.\n      try {\n        cart = await Cart.findOneAndUpdate(\n          { userId },\n          {\n            $setOnInsert: { userId },\n            $push: {\n              items: {\n                productId: new mo",
      "ngoose.Types.ObjectId(productId),\n                name: product.name,\n                price: product.price,\n                quantity,\n                image: product.image,\n              },\n            },\n          },\n          { new: true, upsert: true }\n        );\n      } catch (raceError: any) {\n        // Duplicate-key error from the rare upsert race -- retry once\n        // as a normal update now that the cart definitely exists.\n        if (raceError?.code === 11000) {\n          cart = await Cart.findOneAndUpdate(\n            { userId },\n            {\n              $push: {\n                items: {\n                  productId: new mongoose.Types.ObjectId(productId),\n                  name: product.name,\n                  price: product.price,\n                  quantity,\n                  image: product.image,\n                },\n              },\n            },\n            { new: true }\n          );\n        } else {\n          throw raceError;\n        }\n      }\n    }\n\n    if (!cart) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Unable to add product to cart.\",\n        },\n        { status: 500 }\n      );\n    }\n\n    return NextResponse.json({\n      success: true,\n      message: \"Product added to cart.\",\n      cart,\n    });\n  } catch (error) {\n    console.error(\"POST cart error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to add product to cart.\",\n        debug:\n          error instanceof Error ? error.message : String(error),\n      },\n      { status: 500 }\n    );\n  }\n}\nexport async function PATCH(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const body = await request.json();\n\n    const productId ",
      "= body.productId;\n    const quantity = Number(body.quantity);\n\n    if (\n      !productId ||\n      !mongoose.Types.ObjectId.isValid(productId)\n    ) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Valid product ID is required.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    if (!Number.isInteger(quantity) || quantity < 1) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Quantity must be at least 1.\",\n        },\n        { status: 400 }\n      );\n    }\n\n    const product = await Product.findById(productId).lean();\n\n    if (!product) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Product not found.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    if (quantity > product.stock) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: `Only ${product.stock} items are available.`,\n        },\n        { status: 400 }\n      );\n    }\n\n    const cart = await Cart.findOne({ userId });\n\n    if (!cart) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Cart not found.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    const item = cart.items.find(\n      (cartItem) =>\n        cartItem.productId.toString() === productId\n    );\n\n    if (!item) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Product is not in the cart.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    item.quantity = quantity;\n    item.price = product.price;\n    item.name = product.name;\n    item.image = product.image;\n\n    await cart.save();\n\n    return NextResponse.json({\n      success: true,\n      message: \"Cart updated successfully.\",\n      cart,\n    });\n  } catch (error) {\n    console.error(\"PATCH cart error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to update cart.\",\n      },\n      { status: 500",
      " }\n    );\n  }\n}\nexport async function DELETE(request: NextRequest) {\n  try {\n    await connectDB();\n\n    const userId = getUserId(request);\n\n    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"User ID is required.\",\n        },\n        { status: 401 }\n      );\n    }\n\n    const { searchParams } = new URL(request.url);\n    const productId =\n      searchParams.get(\"productId\")?.trim() || \"\";\n\n    if (productId) {\n      if (!mongoose.Types.ObjectId.isValid(productId)) {\n        return NextResponse.json(\n          {\n            success: false,\n            message: \"Invalid product ID.\",\n          },\n          { status: 400 }\n        );\n      }\n\n      const cart = await Cart.findOne({ userId });\n\n      if (!cart) {\n        return NextResponse.json({\n          success: true,\n          message: \"Cart is already empty.\",\n          cart: {\n            userId,\n            items: [],\n          },\n        });\n      }\n\n      cart.items = cart.items.filter(\n        (item) =>\n          item.productId.toString() !== productId\n      );\n\n      await cart.save();\n\n      return NextResponse.json({\n        success: true,\n        message: \"Product removed from cart.\",\n        cart,\n      });\n    }\n\n    await Cart.findOneAndDelete({ userId });\n\n    return NextResponse.json({\n      success: true,\n      message: \"Cart cleared successfully.\",\n      cart: {\n        userId,\n        items: [],\n      },\n    });\n  } catch (error) {\n    console.error(\"DELETE cart error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to update cart.\",\n      },\n      { status: 500 }\n    );\n  }\n}\n\n"
    ]
  },
{
    "file": "src/app/products/[slug]/page.tsx",
    "old": "  const [message, setMessage] = useState(\"\");",
    "new": "  const [message, setMessage] = useState(\"\");\n  const [messageIsError, setMessageIsError] = useState(false);"
  },
  {
    "file": "src/app/products/[slug]/page.tsx",
    "old": "      setMessage(\"This product is out of stock.\");",
    "new": "      setMessageIsError(true);\n      setMessage(\"This product is out of stock.\");"
  },
  {
    "file": "src/app/products/[slug]/page.tsx",
    "old": "      if (!response.ok || !data.success) {\n        throw new Error(\n          data.message ||\n            \"Unable to add product to cart.\"\n        );\n      }",
    "new": "      if (!response.ok || !data.success) {\n        throw new Error(\n          data.debug\n            ? `${data.message || \"Unable to add product to cart.\"} (${data.debug})`\n            : data.message || \"Unable to add product to cart.\"\n        );\n      }"
  },
  {
    "file": "src/app/products/[slug]/page.tsx",
    "old": "      return true;\n    } catch (err) {\n      setMessage(\n        err instanceof Error\n          ? err.message\n          : \"Unable to add product to cart.\"\n      );\n      return false;\n    }\n  }\n\n  async function handleAddToCart() {\n    try {\n      setAdding(true);\n      setMessage(\"\");\n\n      const success = await addToCart();\n\n      if (success) {\n        setMessage(`${product?.name} added to cart.`);\n      }\n    } finally {\n      setAdding(false);\n    }\n  }\n\n  async function handleBuyNow() {\n    try {\n      setBuying(true);\n      setMessage(\"\");\n\n      const success = await addToCart();",
    "new": "      return true;\n    } catch (err) {\n      setMessageIsError(true);\n      setMessage(\n        err instanceof Error\n          ? err.message\n          : \"Unable to add product to cart.\"\n      );\n      return false;\n    }\n  }\n\n  async function handleAddToCart() {\n    try {\n      setAdding(true);\n      setMessage(\"\");\n      setMessageIsError(false);\n\n      const success = await addToCart();\n\n      if (success) {\n        setMessageIsError(false);\n        setMessage(`${product?.name} added to cart.`);\n      }\n    } finally {\n      setAdding(false);\n    }\n  }\n\n  async function handleBuyNow() {\n    try {\n      setBuying(true);\n      setMessage(\"\");\n      setMessageIsError(false);\n\n      const success = await addToCart();"
  },
{
    "file": "src/app/products/[slug]/page.tsx",
    "old": "        {message && (\n          <div className=\"mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700\">\n            ✓ {message}\n          </div>\n        )}",
    "new": "        {message && (\n          <div\n            className={\n              messageIsError\n                ? \"mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700\"\n                : \"mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700\"\n            }\n          >\n            {messageIsError ? \"✗\" : \"✓\"} {message}\n          </div>\n        )}"
  }
]''')

applied = 0
skipped = 0
errors = 0

by_file = {}
for p in PATCHES:
    by_file.setdefault(p["file"], []).append(p)

for rel, plist in by_file.items():
    full = os.path.join(ROOT, rel)
    if not os.path.exists(full):
        print(f"[SKIP] file not found: {rel}")
        errors += len(plist)
        continue
    with open(full, encoding="utf-8") as f:
        content = f.read()
    for p in plist:
        old = join_chunks(p["old"])
        new = join_chunks(p["new"])
        if new in content:
            print(f"[SKIP] already applied: {rel}")
            skipped += 1
            continue
        if content.count(old) != 1:
            print(f"[CHECK] anchor not found -- please check manually: {rel}")
            errors += 1
            continue
        content = content.replace(old, new)
        print(f"[OK] updated: {rel}")
        applied += 1
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
print()
print("----------------------------------------")
print(f"Applied: {applied}   Skipped: {skipped}   Needs manual check: {errors}")
print("----------------------------------------")
if errors:
    print("Some parts could not be auto-applied -- please review the [CHECK] lines manually.")
