#!/usr/bin/env python3
import json, os

ROOT = os.getcwd()

DATA = json.loads(r'''{
  "patches": [
    {
      "file": "src/app/admin/orders/page.tsx",
      "old": "                    </select>\n                  </div>",
      "new": "                    </select>\n\n                    <Link\n                      href={`/admin/orders/${order._id}/invoice`}\n                      target=\"_blank\"\n                      rel=\"noopener noreferrer\"\n                      style={{\n                        display: \"inline-flex\",\n                        alignItems: \"center\",\n                        padding: \"9px 12px\",\n                        borderRadius: \"8px\",\n                        background: \"#059669\",\n                        color: \"#fff\",\n                        fontWeight: 700,\n                        fontSize: \"13px\",\n                        textDecoration: \"none\",\n                        whiteSpace: \"nowrap\",\n                      }}\n                    >\n                      🧾 Invoice\n                    </Link>\n                  </div>"
    }
  ],
  "new_files_chunked": {
    "src/app/api/admin/orders/[id]/route.ts": [
      "import { NextRequest, NextResponse } from \"next/server\";\nimport connectDB from \"@/lib/mongodb\";\nimport Order from \"@/models/Order\";\n\nexport async function GET(\n  request: NextRequest,\n  { params }: { params: Promise<{ id: string }> }\n) {\n  try {\n    await connectDB();\n\n    const { id } = await params;\n\n    const order = await Order.findById(id)\n      .populate(\"userId\", \"fullName phone email\")\n      .lean();\n\n    if (!order) {\n      return NextResponse.json(\n        {\n          success: false,\n          message: \"Order not found.\",\n        },\n        { status: 404 }\n      );\n    }\n\n    return NextResponse.json({\n      success: true,\n      order,\n    });\n  } catch (error) {\n    console.error(\"GET admin order by id error:\", error);\n\n    return NextResponse.json(\n      {\n        success: false,\n        message: \"Unable to load order.\",\n      },\n      { status: 500 }\n    );\n  }\n}\n"
    ],
    "src/app/admin/orders/[id]/invoice/page.tsx": [
      "\"use client\";\n\nimport { useEffect, useState, use as usePromise } from \"react\";\nimport Link from \"next/link\";\n\ntype OrderItem = {\n  productId: string;\n  name: string;\n  price: number;\n  quantity: number;\n  image?: string;\n};\n\ntype Order = {\n  _id: string;\n  customerName: string;\n  customerPhone: string;\n  customerEmail?: string;\n  items: OrderItem[];\n  totalAmount: number;\n  currency: string;\n  paymentMethod: string;\n  paymentStatus: \"pending\" | \"paid\" | \"failed\";\n  status:\n    | \"pending\"\n    | \"confirmed\"\n    | \"processing\"\n    | \"shipped\"\n    | \"delivered\"\n    | \"cancelled\";\n  deliveryAddress: {\n    fullName: string;\n    phone: string;\n    address: string;\n    city?: string;\n    area?: string;\n  };\n  createdAt?: string;\n};\n\nexport default function OrderInvoicePage({\n  params,\n}: {\n  params: Promise<{ id: string }>;\n}) {\n  const { id } = usePromise(params);\n\n  const [order, setOrder] = useState<Order | null>(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(\"\");\n\n  useEffect(() => {\n    let cancelled = false;\n\n    async function loadOrder() {\n      try {\n        setLoading(true);\n        setError(\"\");\n\n        const response = await fetch(`/api/admin/orders/${id}`, {\n          cache: \"no-store\",\n        });\n\n        const data = await response.json();\n\n        if (!response.ok || !data.success) {\n          throw new Error(\n            data.message || \"Unable to load order.\"\n          );\n        }\n\n        if (!cancelled) {\n          setOrder(data.order);\n        }\n      } catch (err) {\n        if (!cancelled) {\n          setError(\n            err instanceof Error\n              ? err.message\n              : \"Unable to load order.\"\n          );\n        }\n      } finally {\n        if (!cancelled) {\n          setLoading(false);\n        }\n      }\n    }\n\n    loadOrder();\n\n    return () => {\n      cancelled = true;\n    };\n  }, [id]);\n\n  return (\n    <>\n      {/* Print rules: hide screen-only chrome, force clean white\n          pag",
      "e for printing / \"Save as PDF\". */}\n      <style>{`\n        @media print {\n          .invoice-no-print {\n            display: none !important;\n          }\n          .invoice-page {\n            box-shadow: none !important;\n            border: none !important;\n            margin: 0 !important;\n            padding: 0 !important;\n            max-width: 100% !important;\n          }\n          body {\n            background: #ffffff !important;\n          }\n        }\n\n        @page {\n          size: A4;\n          margin: 14mm;\n        }\n      `}</style>\n\n      <main\n        style={{\n          minHeight: \"100vh\",\n          background: \"#e2e8f0\",\n          padding: \"24px 16px 60px\",\n        }}\n      >\n        <div\n          className=\"invoice-no-print\"\n          style={{\n            maxWidth: \"820px\",\n            margin: \"0 auto 18px\",\n            display: \"flex\",\n            justifyContent: \"space-between\",\n            alignItems: \"center\",\n            gap: \"12px\",\n            flexWrap: \"wrap\",\n          }}\n        >\n          <Link\n            href=\"/admin/orders\"\n            style={{\n              display: \"inline-flex\",\n              padding: \"10px 15px\",\n              borderRadius: \"9px\",\n              background: \"#0f172a\",\n              border: \"1px solid #334155\",\n              color: \"#fff\",\n              textDecoration: \"none\",\n              fontSize: \"14px\",\n            }}\n          >\n            {\"← Back to Orders\"}\n          </Link>\n\n          {order && (\n            <button\n              onClick={() => window.print()}\n              style={{\n                padding: \"10px 18px\",\n                borderRadius: \"9px\",\n                border: \"1px solid #2563eb\",\n                background: \"#2563eb\",\n                color: \"#fff\",\n                fontWeight: 700,\n                cursor: \"pointer\",\n                fontSize: \"14px\",\n              }}\n            >\n              🖨️ Print / Save as PDF\n            </button>\n          )}\n        </div>\n\n        {loading &&",
      " (\n          <div\n            className=\"invoice-no-print\"\n            style={{\n              maxWidth: \"820px\",\n              margin: \"0 auto\",\n              textAlign: \"center\",\n              color: \"#334155\",\n              padding: \"40px\",\n            }}\n          >\n            Loading invoice...\n          </div>\n        )}\n\n        {!loading && error && (\n          <div\n            className=\"invoice-no-print\"\n            style={{\n              maxWidth: \"820px\",\n              margin: \"0 auto\",\n              background: \"#fee2e2\",\n              color: \"#7f1d1d\",\n              padding: \"16px\",\n              borderRadius: \"10px\",\n              fontWeight: 600,\n            }}\n          >\n            {error}\n          </div>\n        )}\n\n        {!loading && order && (\n          <div\n            className=\"invoice-page\"\n            style={{\n              maxWidth: \"820px\",\n              margin: \"0 auto\",\n              background: \"#ffffff\",\n              color: \"#0f172a\",\n              borderRadius: \"10px\",\n              boxShadow: \"0 10px 30px rgba(0,0,0,0.15)\",\n              padding: \"40px\",\n            }}\n          >\n            {/* Header */}\n            <div\n              style={{\n                display: \"flex\",\n                justifyContent: \"space-between\",\n                alignItems: \"flex-start\",\n                gap: \"20px\",\n                flexWrap: \"wrap\",\n                borderBottom: \"3px solid #0f172a\",\n                paddingBottom: \"18px\",\n                marginBottom: \"24px\",\n              }}\n            >\n              <div>\n                <div\n                  style={{\n                    fontSize: \"26px\",\n                    fontWeight: 900,\n                    letterSpacing: \"0.5px\",\n                  }}\n                >\n                  🛍️ TechStar\n                </div>\n                <div\n                  style={{\n                    marginTop: \"4px\",\n                    fontSize: \"13px\",\n                    color: \"#475569\",\n         ",
      "         }}\n                >\n                  Order Invoice &amp; Shipping Label\n                </div>\n              </div>\n\n              <div style={{ textAlign: \"right\" }}>\n                <div\n                  style={{\n                    fontSize: \"13px\",\n                    color: \"#64748b\",\n                  }}\n                >\n                  Order No.\n                </div>\n                <div\n                  style={{\n                    fontSize: \"20px\",\n                    fontWeight: 800,\n                    letterSpacing: \"0.5px\",\n                  }}\n                >\n                  #{order._id.slice(-8).toUpperCase()}\n                </div>\n                <div\n                  style={{\n                    marginTop: \"6px\",\n                    fontSize: \"13px\",\n                    color: \"#64748b\",\n                  }}\n                >\n                  {order.createdAt\n                    ? new Date(order.createdAt).toLocaleString()\n                    : \"Date unavailable\"}\n                </div>\n              </div>\n            </div>\n\n            {/* Ship To -- large & prominent so this section can be\n                cut out / read at a glance when stuck on the parcel */}\n            <div\n              style={{\n                border: \"2px solid #0f172a\",\n                borderRadius: \"10px\",\n                padding: \"18px 20px\",\n                marginBottom: \"24px\",\n              }}\n            >\n              <div\n                style={{\n                  fontSize: \"12px\",\n                  fontWeight: 800,\n                  letterSpacing: \"1px\",\n                  color: \"#64748b\",\n                  marginBottom: \"8px\",\n                }}\n              >\n                📦 SHIP TO\n              </div>\n\n              <div\n                style={{\n                  fontSize: \"22px\",\n                  fontWeight: 800,\n                  marginBottom: \"6px\",\n                }}\n              >\n                {order.deliveryAddress?.full",
      "Name ||\n                  order.customerName}\n              </div>\n\n              <div\n                style={{\n                  fontSize: \"16px\",\n                  lineHeight: 1.5,\n                  marginBottom: \"6px\",\n                }}\n              >\n                {order.deliveryAddress?.address}\n                {order.deliveryAddress?.area\n                  ? `, ${order.deliveryAddress.area}`\n                  : \"\"}\n                {order.deliveryAddress?.city\n                  ? `, ${order.deliveryAddress.city}`\n                  : \"\"}\n              </div>\n\n              <div\n                style={{\n                  fontSize: \"16px\",\n                  fontWeight: 700,\n                }}\n              >\n                📱{\" \"}\n                {order.deliveryAddress?.phone ||\n                  order.customerPhone}\n              </div>\n            </div>\n\n            {/* Order meta */}\n            <div\n              style={{\n                display: \"grid\",\n                gridTemplateColumns:\n                  \"repeat(auto-fit, minmax(150px, 1fr))\",\n                gap: \"12px\",\n                marginBottom: \"24px\",\n                fontSize: \"13px\",\n              }}\n            >\n              <div>\n                <div style={{ color: \"#64748b\" }}>\n                  Customer\n                </div>\n                <div style={{ fontWeight: 700 }}>\n                  {order.customerName}\n                </div>\n              </div>\n\n              <div>\n                <div style={{ color: \"#64748b\" }}>\n                  Email\n                </div>\n                <div style={{ fontWeight: 700 }}>\n                  {order.customerEmail || \"—\"}\n                </div>\n              </div>\n\n              <div>\n                <div style={{ color: \"#64748b\" }}>\n                  Order Status\n                </div>\n                <div\n                  style={{\n                    fontWeight: 700,\n                    textTransform: \"capitalize\",\n                  }",
      "}\n                >\n                  {order.status}\n                </div>\n              </div>\n\n              <div>\n                <div style={{ color: \"#64748b\" }}>\n                  Payment\n                </div>\n                <div\n                  style={{\n                    fontWeight: 700,\n                    textTransform: \"capitalize\",\n                  }}\n                >\n                  {order.paymentMethod} ·{\" \"}\n                  {order.paymentStatus}\n                </div>\n              </div>\n            </div>\n\n            {/* Items table */}\n            <table\n              style={{\n                width: \"100%\",\n                borderCollapse: \"collapse\",\n                fontSize: \"14px\",\n                marginBottom: \"20px\",\n              }}\n            >\n              <thead>\n                <tr style={{ background: \"#0f172a\", color: \"#fff\" }}>\n                  <th\n                    style={{\n                      textAlign: \"left\",\n                      padding: \"10px 12px\",\n                    }}\n                  >\n                    #\n                  </th>\n                  <th\n                    style={{\n                      textAlign: \"left\",\n                      padding: \"10px 12px\",\n                    }}\n                  >\n                    Product\n                  </th>\n                  <th\n                    style={{\n                      textAlign: \"center\",\n                      padding: \"10px 12px\",\n                    }}\n                  >\n                    Qty\n                  </th>\n                  <th\n                    style={{\n                      textAlign: \"right\",\n                      padding: \"10px 12px\",\n                    }}\n                  >\n                    Unit Price\n                  </th>\n                  <th\n                    style={{\n                      textAlign: \"right\",\n                      padding: \"10px 12px\",\n                    }}\n                  >\n              ",
      "      Subtotal\n                  </th>\n                </tr>\n              </thead>\n\n              <tbody>\n                {order.items.map((item, index) => (\n                  <tr\n                    key={`${item.productId}-${index}`}\n                    style={{\n                      borderBottom: \"1px solid #e2e8f0\",\n                      background:\n                        index % 2 === 0 ? \"#ffffff\" : \"#f8fafc\",\n                    }}\n                  >\n                    <td style={{ padding: \"10px 12px\" }}>\n                      {index + 1}\n                    </td>\n                    <td style={{ padding: \"10px 12px\" }}>\n                      {item.name}\n                    </td>\n                    <td\n                      style={{\n                        padding: \"10px 12px\",\n                        textAlign: \"center\",\n                      }}\n                    >\n                      {item.quantity}\n                    </td>\n                    <td\n                      style={{\n                        padding: \"10px 12px\",\n                        textAlign: \"right\",\n                      }}\n                    >\n                      {order.currency} {item.price}\n                    </td>\n                    <td\n                      style={{\n                        padding: \"10px 12px\",\n                        textAlign: \"right\",\n                        fontWeight: 700,\n                      }}\n                    >\n                      {order.currency}{\" \"}\n                      {item.price * item.quantity}\n                    </td>\n                  </tr>\n                ))}\n              </tbody>\n            </table>\n\n            {/* Total */}\n            <div\n              style={{\n                display: \"flex\",\n                justifyContent: \"flex-end\",\n                marginBottom: \"28px\",\n              }}\n            >\n              <div\n                style={{\n                  minWidth: \"240px\",\n                  border: \"2px solid ",
      "#0f172a\",\n                  borderRadius: \"10px\",\n                  padding: \"14px 18px\",\n                  display: \"flex\",\n                  justifyContent: \"space-between\",\n                  alignItems: \"center\",\n                }}\n              >\n                <span style={{ fontWeight: 700 }}>\n                  Total Amount\n                </span>\n                <span\n                  style={{\n                    fontSize: \"22px\",\n                    fontWeight: 900,\n                  }}\n                >\n                  {order.currency} {order.totalAmount}\n                </span>\n              </div>\n            </div>\n\n            {/* Footer */}\n            <div\n              style={{\n                borderTop: \"1px solid #e2e8f0\",\n                paddingTop: \"16px\",\n                fontSize: \"12px\",\n                color: \"#64748b\",\n                textAlign: \"center\",\n              }}\n            >\n              Thank you for shopping with TechStar. For any\n              questions about this order, please contact our\n              support team with the Order No. shown above.\n            </div>\n          </div>\n        )}\n      </main>\n    </>\n  );\n}\n"
    ]
  }
}''')

applied = 0
skipped = 0
errors = 0

# 1) Text patch on the existing orders list page
for p in DATA["patches"]:
    full = os.path.join(ROOT, p["file"])
    if not os.path.exists(full):
        print(f"[SKIP] file not found: {p['file']}")
        errors += 1
        continue
    with open(full, encoding="utf-8") as f:
        content = f.read()
    if p["new"] in content:
        print(f"[SKIP] already applied: {p['file']}")
        skipped += 1
        continue
    if content.count(p["old"]) != 1:
        print(f"[CHECK] anchor not found -- please check manually: {p['file']}")
        errors += 1
        continue
    content = content.replace(p["old"], p["new"])
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[OK] updated: {p['file']}")
    applied += 1

# 2) New files (order-by-id API route + invoice page), content stored
#    as chunks so no single line in this script is too long to paste.
for rel, chunks in DATA["new_files_chunked"].items():
    full = os.path.join(ROOT, rel)
    if os.path.exists(full):
        print(f"[SKIP] already exists: {rel}")
        skipped += 1
        continue
    file_content = "".join(chunks)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(file_content)
    print(f"[OK] created: {rel}")
    applied += 1

print()
print("----------------------------------------")
print(f"Applied: {applied}   Skipped: {skipped}   Needs manual check: {errors}")
print("----------------------------------------")
if errors:
    print("Some parts could not be auto-applied -- please review the [CHECK] lines manually.")
