import { getSiteSettings } from "@/lib/siteSettings";
import Link from "next/link";

export default async function AdminDashboard() {
  const site = await getSiteSettings();
  const cardStyle = {
      textDecoration: "none",
          color: "white",
              background: "#0f172a",
                  padding: "25px",
                      borderRadius: "18px",
                          border: "1px solid #1e293b",
                              display: "block",
                                };

                                  return (
                                      <main
                                            style={{
                                                    minHeight: "100vh",
                                                            background: "#020617",
                                                                    color: "white",
                                                                            padding: "30px 20px",
                                                                                  }}
                                                                                      >
                                                                                            <div
                                                                                                    style={{
                                                                                                              maxWidth: "1000px",
                                                                                                                        margin: "0 auto",
                                                                                                                                }}
                                                                                                                                      >
                                                                                                                                              <h1
                                                                                                                                                        style={{
                                                                                                                                                                    fontSize: "32px",
                                                                                                                                                                                fontWeight: 800,
                                                                                                                                                                                            marginBottom: "8px",
                                                                                                                                                                                                      }}
                                                                                                                                                                                                              >
                                                                                                                                                                                                                        {site.siteName} Admin Dashboard
                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                        <p
                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                              color: "#94a3b8",
                                                                                                                                                                                                                                                                          marginBottom: "30px",
                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                      Welcome, {site.siteName} Admin
                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                            display: "grid",
                                                                                                                                                                                                                                                                                                                                                        gridTemplateColumns:
                                                                                                                                                                                                                                                                                                                                                                      "repeat(auto-fit, minmax(220px, 1fr))",
                                                                                                                                                                                                                                                                                                                                                                                  gap: "20px",
                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>🏠 Home</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Visit {site.siteName} website
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/admin/products" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>📦 Products</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Product management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/admin/orders" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>🛒 Orders</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Order management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link href="/admin/users" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>👥 Users</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      User management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

          <Link href="/admin/banners" style={cardStyle}>
            <h2>🖼️ Banners</h2>
            <p style={{ color: "#94a3b8" }}>
              Homepage banner management
            </p>
          </Link>

          <Link href="/admin/analytics" style={cardStyle}>
            <h2>📊 Analytics</h2>
            <p style={{ color: "#94a3b8" }}>
              Revenue, sales trend & best sellers
            </p>
          </Link>

          <Link href="/admin/marketplace" style={cardStyle}>
            <h2>🏪 Marketplace</h2>
            <p style={{ color: "#94a3b8" }}>
              Vendors, commission & payouts
            </p>
          </Link>

          <Link href="/admin/commission" style={cardStyle}>
            <h2>🧾 COD commission</h2>
            <p style={{ color: "#94a3b8" }}>
              Vendor dues, monthly lock & payments
            </p>
          </Link>

          <Link href="/admin/pricing" style={cardStyle}>
            <h2>🚚 Commission & courier</h2>
            <p style={{ color: "#94a3b8" }}>
              Commission limits and courier charges
            </p>
          </Link>

          <Link href="/admin/site-settings" style={cardStyle}>
            <h2>🌐 Website settings</h2>
            <p style={{ color: "#94a3b8" }}>
              Name, logo and contact info
            </p>
          </Link>

          <Link href="/admin/coupons" style={cardStyle}>
            <h2>🎟️ Coupons</h2>
            <p style={{ color: "#94a3b8" }}>
              Create and manage discount codes
            </p>
          </Link>

          <Link href="/admin/notifications" style={cardStyle}>
            <h2>🔔 Notifications</h2>
            <p style={{ color: "#94a3b8" }}>
              Send offers to all customers
            </p>
          </Link>

          <Link href="/admin/reviews" style={cardStyle}>
            <h2>⭐ Reviews</h2>
            <p style={{ color: "#94a3b8" }}>
              Moderate customer product reviews
            </p>
          </Link>

          <Link href="/admin/requests" style={cardStyle}>
            <h2>↩️ Returns & refunds</h2>
            <p style={{ color: "#94a3b8" }}>
              Return, refund and exchange requests
            </p>
          </Link>

          <Link href="/admin/chats" style={cardStyle}>
            <h2>💬 Chats & support inbox</h2>
            <p style={{ color: "#94a3b8" }}>
              Customer questions and vendor chat monitor
            </p>
          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: "30px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: "inline-block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "12px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: "#2563eb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {"← Back to Website"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }