import Link from "next/link";

export default function AdminDashboard() {
  const cardStyle = {
      textDecoration: "none",
          color: "white",
              background: "#0f172a",
                  padding: "25px",
                      borderRadius: "18px",
                          border: "1px solid #1e293b",
                              display: "block",
                                };

                                  return (
                                      <main
                                            style={{
                                                    minHeight: "100vh",
                                                            background: "#020617",
                                                                    color: "white",
                                                                            padding: "30px 20px",
                                                                                  }}
                                                                                      >
                                                                                            <div
                                                                                                    style={{
                                                                                                              maxWidth: "1000px",
                                                                                                                        margin: "0 auto",
                                                                                                                                }}
                                                                                                                                      >
                                                                                                                                              <h1
                                                                                                                                                        style={{
                                                                                                                                                                    fontSize: "32px",
                                                                                                                                                                                fontWeight: 800,
                                                                                                                                                                                            marginBottom: "8px",
                                                                                                                                                                                                      }}
                                                                                                                                                                                                              >
                                                                                                                                                                                                                        TechStar Admin Dashboard
                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                        <p
                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                              color: "#94a3b8",
                                                                                                                                                                                                                                                                          marginBottom: "30px",
                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                      Welcome, TechStar Admin
                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                            display: "grid",
                                                                                                                                                                                                                                                                                                                                                        gridTemplateColumns:
                                                                                                                                                                                                                                                                                                                                                                      "repeat(auto-fit, minmax(220px, 1fr))",
                                                                                                                                                                                                                                                                                                                                                                                  gap: "20px",
                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>🏠 Home</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Visit TechStar website
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/admin/products" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>📦 Products</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Product management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/admin/orders" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>🛒 Orders</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Order management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link href="/admin/users" style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>👥 Users</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style={{ color: "#94a3b8" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      User management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

          <Link href="/admin/banners" style={cardStyle}>
            <h2>🖼️ Banners</h2>
            <p style={{ color: "#94a3b8" }}>
              Homepage banner management
            </p>
          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: "30px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: "inline-block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "12px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: "#2563eb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ← Back to Website
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }